import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import DarkModeProvider from "@/components/DarkModeProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "JobGen App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased no-scrollbar`}>
        <DarkModeProvider>
          <Navbar />
          <main>{children}</main>
        </DarkModeProvider>
      </body>
    </html>
  );
}
